const myFunc = require("./foo.js");
const {MyClass , Math} = require("./file_24");
let one = new Math(1 , 2 , 0);
let two = new MyClass('RUDRA+++');
two.greet();
console.log(one.coordinates());
const a = myFunc.sampleFunc();
const b = myFunc.sampleFunc1();
console.log(a);
console.log(b);
